language: php

matrix:
  include:
    - php: 7.4
env:
  global:
    - XDEBUG_MODE: coverage,debug
install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction
  - travis_retry composer require --dev php-coveralls/php-coveralls

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
